USE bank;
SELECT * FROM deposit;
SELECT * FROM borrow;
SELECT * FROM customer;
SELECT * FROM branch;
SELECT actno,amount FROM deposit;
SELECT cname, actno FROM deposit;
SELECT cname FROM customer;
SELECT bname FROM branch;
SELECT cname FROM borrow;
SELECT cname FROM customer WHERE city LIKE "NAGPUR";
SELECT cname FROM deposit WHERE amount > 4000;
SELECT adate FROM deposit WHERE cname LIKE "Anil";
SELECT bname FROM branch WHERE city LIKE "BOMBAY";
SELECT cname FROM borrow WHERE loanno LIKE "L206";
SELECT cname FROM deposit WHERE bname = "VRCE";
SELECT bname FROM branch WHERE city LIKE "DELHI";
SELECT actno, amount FROM deposit WHERE adate > "1996-12-01" AND adate < "1995-05-01";
SELECT city FROM branch WHERE bname LIKE "KAROLBAGH";
SELECT * FROM customer WHERE cname LIKE "Anil";